# --- AUTOSTART ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = hyprpaper -c ~/.config/hyprpaper/hyprpaper.conf
exec-once = nm-applet --indicator
