# ==========================================
# HYPRLAND - CONFIGURACIÓN MÍNIMA
# ==========================================

# --- MONITOR Y TECLADO ---
monitor=,preferred,auto,1

input {
    kb_layout = us
}

# --- ESTÉTICA BASE Y TRANSPARENCIA ---
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

decoration {
    rounding = 8
    active_opacity = 0.85
    inactive_opacity = 0.75
}

# --- ATAJOS BÁSICOS ---
$mainMod = SUPER

# Abrir aplicaciones
bind = $mainMod, Q, exec, kitty
bind = $mainMod, E, exec, dolphin
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, B, exec, firefox

# Control de ventanas
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, V, togglefloating,

# Mover el foco entre ventanas (Flechas)
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d


































































































































































































































































