# ==========================================
# HYPRLAND - MINIMAL CONFIGURATION
# ==========================================

# --- MONITOR & KEYBOARD ---
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60,-1920x0, 1

input {
    kb_layout = us
    kb_variant = intl
}

# --- BASE STETIC AND TRANSPARENCY ---
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(00f0ffff) rgba(ff00d4ff) rgba(ff00d4ff)
col.inactive_border = rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(00f0ffaa) rgba(ff00d4aa) rgba(ff00d4aa)
}

decoration {
    rounding = 8
    active_opacity = 0.95
    inactive_opacity = 0.90
}

animations {
    enabled = yes
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = borderangle, 1, 150, linear, loop
}
    
# --- KEYBINDINGS ---
source = ~/.config/hypr/core/keybinds.conf

# --- AUTOSTART ---
source = ~/.config/hypr/core/autostart.conf

# --- WINDOWRULES --- 
source = ~/.config/hypr/core/windowrules.conf

# --- GLOBAL WORKSPACES ---
# Right monitor (Main)
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1

# Left monitor (Secondary)
workspace = 11, monitor:HDMI-A-1
workspace = 12, monitor:HDMI-A-1
workspace = 13, monitor:HDMI-A-1
workspace = 14, monitor:HDMI-A-1
