# ==========================================
# KITTY CONFIGURATION
# ==========================================

background_opacity 0.30
dynamic_background_opacity yes
inactive_text_alpha 0.70
confirm_os_window_close 0
